window.ATHENA_SCHEMA = {
  version: "0.1.0",
  classes: [
    ["SCN", "Scenario", "Scenario", "scenario_id, name, mission, confidence, status", "contains ThreatEvent 1..*; affects Asset 1..*", "ATHENA KG", "—"],
    ["MIS", "Mission", "Scenario", "mission_id, objective, priority, owner", "supportedBy MultiDomainAsset 1..*", "ATHENA KG", "—"],
    ["OC", "OperationalConstraint", "Scenario", "constraint_id, type, value, unit", "constrains Countermeasure 0..*", "ATHENA KG", "—"],
    ["TE", "ThreatEvent", "Threat Intelligence", "event_id, observed_at, confidence, status", "targets Asset 1..*; uses OffensiveCapability 1..*", "OpenCTI + ATHENA", "Incident / Sighting (partial)"],
    ["ADV", "Adversary", "Threat Intelligence", "opencti_id, stix_id, name, confidence", "performs ThreatEvent 0..*", "OpenCTI", "Threat-Actor / Intrusion-Set"],
    ["CAM", "Campaign", "Threat Intelligence", "opencti_id, stix_id, name, period", "contains ThreatEvent 0..*", "OpenCTI", "Campaign"],
    ["AP", "AttackPattern", "Threat Intelligence", "stix_id, external_id, name", "enables ThreatEvent 0..*", "OpenCTI", "Attack-Pattern"],
    ["MAL", "Malware", "Threat Intelligence", "stix_id, name, family", "usedBy Adversary 0..*", "OpenCTI", "Malware"],
    ["IND", "Indicator", "Threat Intelligence", "stix_id, pattern, valid_from", "indicates ThreatEvent 0..*", "OpenCTI", "Indicator"],
    ["OBS", "Observable", "Threat Intelligence", "stix_id, observable_type, value", "supports Evidence 0..*", "OpenCTI", "STIX Cyber Observable"],
    ["VUL", "Vulnerability", "Threat Intelligence", "stix_id, external_id, severity", "affects MultiDomainAsset 0..*", "OpenCTI", "Vulnerability"],
    ["INF", "Infrastructure", "Threat Intelligence", "stix_id, name, infrastructure_type", "supports ThreatEvent 0..*", "OpenCTI", "Infrastructure"],
    ["MDA", "MultiDomainAsset", "Asset", "asset_id, type, criticality, owner, location", "operatesIn Domain 1..*; supports Mission 1..*", "ATHENA KG", "Custom ATHENA"],
    ["DOM", "Domain", "ATHENA-D", "domain_id, name, description", "classifies Capability 0..*", "ATHENA KG", "Custom ATHENA"],
    ["OCAP", "OffensiveCapability", "ATHENA-D", "capability_id, name, maturity, availability", "belongsTo Domain 1; usedBy Adversary 0..*", "ATHENA KG + OpenCTI refs", "Capability (partial)"],
    ["DCAP", "DefensiveCapability", "ATHENA-D", "capability_id, name, maturity, availability", "requiredBy Countermeasure 0..*", "ATHENA KG", "Custom ATHENA"],
    ["CES", "CapabilityExposureState", "ATHENA-D", "state_id, caexp, confidence, observed_at", "forScenario 1; forDomain 1", "ATHENA KG", "Custom ATHENA"],
    ["PROC", "CybersecurityProcess", "ATHENA-P", "process_id, name, framework_ref", "groups SecurityControl 0..*", "ATHENA KG", "Custom ATHENA"],
    ["CTRL", "SecurityControl", "ATHENA-P", "control_id, name, framework, external_id", "implementedBy Countermeasure 0..*", "ATHENA KG", "Course-of-Action (partial)"],
    ["CSTATE", "ControlState", "ATHENA-P", "state_id, cov, confidence, observed_at", "forScenario 1; forControl 1", "ATHENA KG", "Custom ATHENA"],
    ["SLT", "SecurityLevelType", "ATHENA-L", "level_type_id, name, scale_min, scale_max", "typedBy SecurityLevelState 0..*", "ATHENA KG", "Custom ATHENA"],
    ["SLS", "SecurityLevelState", "ATHENA-L", "state_id, lv, confidence, observed_at", "forScenario 1; forLevelType 1", "ATHENA KG", "Custom ATHENA"],
    ["EDIM", "EffectDimension", "ATHENA-E", "dimension_id, name, description", "classifies Effect 0..*", "ATHENA KG", "Custom ATHENA"],
    ["EFF", "Effect", "ATHENA-E", "effect_id, severity, probability, reversibility", "hasDimension 1; propagatesTo 0..*", "ATHENA KG", "Custom ATHENA"],
    ["ISTATE", "ImpactState", "ATHENA-E", "state_id, ipos, confidence, observed_at", "forScenario 1; forDimension 1", "ATHENA KG", "Custom ATHENA"],
    ["CM", "Countermeasure", "Decision", "countermeasure_id, type, cost, deployment_time, confidence", "mitigates ThreatEvent 0..*; protects Asset 0..*", "ATHENA KG", "Course-of-Action (partial)"],
    ["CMT", "CountermeasureTarget", "Decision", "target_id, target_value, target_type", "forCountermeasure 1; targetsAxis 1", "ATHENA KG", "Custom ATHENA"],
    ["RA", "RiskAssessment", "Decision", "assessment_id, likelihood, impact, risk", "forScenario 1", "ATHENA KG", "Opinion (partial)"],
    ["CME", "CountermeasureEvaluation", "Decision", "evaluation_id, score, residual_risk, rank", "forScenario 1; evaluates Countermeasure 1", "ATHENA KG", "Custom ATHENA"],
    ["DEC", "Decision", "Decision", "decision_id, outcome, rationale, analyst", "selects Countermeasure 0..1", "ATHENA KG", "Opinion / Note (partial)"],
    ["DEP", "Deployment", "Execution / Learning", "deployment_id, start, end, status", "executes Countermeasure 1", "ATHENA KG", "Custom ATHENA"],
    ["OUT", "Outcome", "Execution / Learning", "outcome_id, observed_reduction, mission_impact", "resultsFrom Deployment 1", "ATHENA KG", "Custom ATHENA"],
    ["EVD", "Evidence", "Provenance", "evidence_id, source_type, source_ref, confidence", "supports KnowledgeAssertion 1..*", "OpenCTI + ATHENA", "Report / Note / External Reference"],
    ["KA", "KnowledgeAssertion", "Provenance", "assertion_id, assertion_type, confidence, created_by", "derivedFrom Evidence 1..*", "ATHENA KG", "Opinion / Note (partial)"],
  ].map(([prefix,name,layer,attributes,relationships,source,mapping]) => ({prefix,name,layer,attributes,relationships,source,mapping})),
  relationships: [
    ["contains", "Scenario", "ThreatEvent", "1", "1..*", true],
    ["targets", "ThreatEvent", "MultiDomainAsset", "1..*", "1..*", true],
    ["performedBy", "ThreatEvent", "Adversary", "1..*", "0..*", false],
    ["uses", "ThreatEvent", "OffensiveCapability", "1..*", "1..*", true],
    ["operatesIn", "MultiDomainAsset", "Domain", "1", "1..*", true],
    ["forControl", "ControlState", "SecurityControl", "1", "1", true],
    ["forScenario", "ControlState", "Scenario", "1", "1", true],
    ["forLevelType", "SecurityLevelState", "SecurityLevelType", "1", "1", true],
    ["forDimension", "ImpactState", "EffectDimension", "1", "1", true],
    ["evaluates", "CountermeasureEvaluation", "Countermeasure", "1", "1", true],
    ["resultsFrom", "Outcome", "Deployment", "1", "1", true],
    ["derivedFrom", "KnowledgeAssertion", "Evidence", "1", "1..*", true],
  ],
  pipeline: ["Input classification", "Entity extraction", "OpenCTI query", "Knowledge enrichment", "Scenario graph", "ATHENA state", "Gap analysis", "CM retrieval", "LLM reasoning", "Formal scoring", "Ranking", "Expert validation", "Knowledge update"],
  populationFields: ["record_kind","object_id","class","name","description","scenario_id","source_object_id","relationship_type","target_object_id","attribute_key","attribute_value","datatype","unit","confidence","assertion_type","source_type","source_ref","opencti_id","stix_id","stix_type","external_id","observed_at","valid_from","valid_to","status","classification","mandatory","created_by","notes"],
};
